---
- name: Create Terraform Folder
  file:
    path: '{{ item }}'
    state: directory
  with_items:
  - '{{ scan_folder_location }}/terraform'
  - '{{ scan_folder_location }}/roles/terraform'
  - '{{ scan_folder_location }}/roles/terraform/tasks'